services:
  ros2:
    image: ros2-ws
    container_name: ros2_dev
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw  # Accès au serveur X11
      - ./src:/root/ros2_ws/src:ro           # Montage dynamique du code source
      - ./build:/root/ros2_ws/build       # Build local
      - ./install:/root/ros2_ws/install   # Installation localisée
    network_mode: host                    # Accès réseau direct (utile pour ROS)
    privileged: true                      # Nécessaire pour certains périphériques
    stdin_open: true                      # Mode interactif
    tty: true                             # Terminal alloué
